### PR TITLE
How to password protect a Jekyll Site

### PR DESCRIPTION
**Pull request by ivanoats**

### CODE REVIEW

**Comment by b-long** [comment]
Hi @ivanoats and thanks for the PR! 👍  I've been thinking about how to rate articles and I'm currently looking for some community guidance (see #8 ).  After a quick glance, it seems the article you've linked to is only applicable for sites hosted by Aerobatic.  Is that correct?

**Comment by ivanoats** [comment]
Yes, each static hosting provider would have its own method, if available. Thanks for considering it.

**Comment by b-long** [comment]
As much as I hate to close a PR, I guess it's probably best if we do.  I wonder though, has any discussion begun around standardizing Jekyll authentication using in the model that Aerobatic has implemented?  If this were to become convention, then it would certainly be useful beyond Aerobatic.

**Comment by b-long** [comment]
Hi @ivanoats I'm going to close this PR after all.  Please send more PRs, really enjoy collaborating with you 👍

**Pull request closed without merging**
